### ISSUE TITLE
Edit link to storybook

### ISSUE THREAD

**Issue by cconrad8** [kianamcc/portal-template#4]
Looks like the link is going to github instead of the storybook

[Synapse Web Monorepo Storybook](https://github.com/Sage-Bionetworks/synapse-web-monorepo/tree/main)
A visual showcase of all available components. Explore and understand the UI elements you can use to build and customize your portal.

![image](https://github.com/user-attachments/assets/1976e1d5-9149-4956-88bd-47581a7bebc8)

**Comment by kianamcc** [comment]
Whoops, should be fixed now! @cconrad8
